### ISSUE TITLE
error: Could not resolve "./script"

### ISSUE THREAD

**Issue by StoneMac65** [byeongsu-hong/cw-hyperlane#111]
Hi. i'm facing this issue when I use commands including yarn

`" yarn cw-hpl upload local -n osmo-test-5"`

I tried to use ./esbuild manually but didnt work. it just hang up

```
cw-hyperlane# yarn cw-hpl upload local -n osmo-test-5
✘ [ERROR] Could not resolve "./script"

1 error
node:child_process:929
    throw err;
    ^

Error: Command failed: /root/new-cl/cw-hyperlane/node_modules/@esbuild/linux-x64/bin/esbuild ./script --bundle --outfile=./dist/index.js --platform=node
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at Object.execFileSync (node:child_process:926:15)
    at Object.<anonymous> (/root/new-cl/cw-hyperlane/node_modules/esbuild/bin/esbuild:221:28)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 925187,
  stdout: null,
  stderr: null
}

Node.js v21.6.2


```

**Comment by StoneMac65** [comment]
@dongwu-kim hi. could you take a look a this issue? still cant solve it

**Comment by byeongsu-hong** [comment]
@StoneMac65 Let me check

**Comment by byeongsu-hong** [comment]
@StoneMac65 which branch are you using now? `main` branch is probably broken, so i suggest you try again with `eddy/linter` or `eddy/script-warp`

**Comment by byeongsu-hong** [comment]
It'll work smoothly after these PRs (#103, #104, #105, #109, #113) to get merged

**Comment by StoneMac65** [comment]
thanks for the response. yes I used main branch. will try that those suggested branches and let you know the result

**Comment by byeongsu-hong** [comment]
@StoneMac65 you just mentioned wrong person mate 🤣

**Comment by StoneMac65** [comment]
> @StoneMac65 you just mentioned wrong person mate 🤣

Hahahha. Wow. Its the result of drinking and coding at the same time :))))

**Comment by byeongsu-hong** [comment]
@StoneMac65 We've merged everything i mentioned. Let's see what happened next.

**Comment by StoneMac65** [comment]
> @StoneMac65 We've merged everything i mentioned. Let's see what happened next.

I tried both latest merged and that branch "eddy/linter" . it worked on osmosis and could instantiate the contract. but I tried to change the code to use a custom network that using "ed25519" and rebuilt the repo. I'm stuck on that part

**Comment by byeongsu-hong** [comment]
@StoneMac65 Currently we're supporting only Secp256k1 for now, Is there any chance to use Secp256k1 key scheme? AFAIK current Cosmos utilizing ed25519 as only for concensus validation purpose, So is the "custom network" that you said custom cosmos sdk chain that supports ed25519 account?

**Comment by byeongsu-hong** [comment]
> I tried both latest merged and that branch "eddy/linter" . it worked on osmosis and could instantiate the contract.

Closing this issue, and let's keep discussing about "ed25519" in this issue. https://github.com/many-things/cw-hyperlane/issues/124
